import { SiteHeader } from "@/components/site-header";
import { DocumentLink } from "@/components/document-link";
import { ExhibitionStart } from "@/features/farm/exhibition-start";
export default function Home() {
  return <main><SiteHeader current="/" /><section className="hero"><div><p className="eyebrow">Your farm companion · Sehore, Madhya Pradesh</p><h1>Plan. Monitor. Improve.</h1><p className="lede">Keep your crop season in one place—from your field and personal plans to observations, costs and harvest records. Your records stay on this device.</p><div className="button-row"><DocumentLink className="button button-primary" href="/today">Open Today</DocumentLink><DocumentLink className="button button-secondary" href="/farm">Set up My Farm</DocumentLink></div></div><div className="hero-note"><strong>Initial focus</strong><span>Soybean · wheat · gram</span><p>Local records and personal reminders work now. Agricultural recommendations wait for reviewed evidence; disease screening has separate model coverage.</p></div></section>
    <section className="principles" aria-label="Farm companion journeys"><div className="principle-grid">{[["01","Plan your season","Choose a crop cycle, prepare your inputs and keep your own reminders.","/plan"],["02","Monitor your field","Review weather availability, track due tasks and record observations.","/today"],["03","Improve your records","Review entered costs, harvests and sales with gaps and synthetic data kept visible.","/records"]].map(([number,title,description,href])=><article key={href}><span>{number}</span><h2>{title}</h2><p>{description}</p><DocumentLink href={href}>Open {title.split(' ')[0]} →</DocumentLink></article>)}</div></section>
    <ExhibitionStart /><section className="device-note"><strong>Leaf screening is one supporting tool.</strong> The existing baseline supports bell pepper, potato and tomato; soybean, wheat and chickpea screening remains unsupported. <DocumentLink href="/scan">Open Scan →</DocumentLink></section>
    <aside className="responsibility-note"><strong>Know what the app can tell you</strong><p>GPS does not measure soil nutrients. Weather is an estimate. Recorded receipts minus costs are not complete profit. Preliminary screening is not a diagnosis; important crop decisions need local expert review.</p></aside></main>;
}
