export const SHELL_PREFIX='agrirakshak-shell-';
export function workerSource(pack) {
  if(!/^[a-f0-9]{20}$/.test(pack.version) || !Array.isArray(pack.assets) || !Array.isArray(pack.pages) || pack.pages.length!==6)throw new Error('Invalid offline build manifest.');
  const paths=[...pack.assets,...pack.pages.map(p=>p.asset)];
  if(!pack.assets.length || new Set(pack.assets).size!==pack.assets.length)throw new Error('Offline assets must be present and unique.');
  if(paths.some(p=>typeof p!=='string' || /[?#]|\.\.|^\/\//.test(p) || !(p.startsWith('/_next/static/') || p.startsWith(`/offline/${pack.version}/`))))throw new Error('Unsafe offline asset path.');
  const routes=['/','/farm','/plan','/today','/records','/scan'];
  if(new Set(pack.pages.map(p=>p.path)).size!==6 || pack.pages.some(p=>!routes.includes(p.path) || p.asset!==`/offline/${pack.version}/${p.path==='/' ? 'index' : p.path.slice(1)}.html`) || pack.assets.some(p=>!p.startsWith('/_next/static/') || !/\.(js|css|woff2?)$/.test(p)))throw new Error('Only app pages and compiled assets can be cached.');
  return `/* Generated by the local build; caches app files only. */\n(${workerRuntime.toString()})(self,${JSON.stringify(pack)});\n`;
}
function workerRuntime(scope,pack) {
  const prefix='agrirakshak-shell-',cacheName=prefix+pack.version;
  const pages=new Map(pack.pages.map(p=>[p.path,p.asset])),urls=[...pack.assets,...pages.values()];
  let preparing=null;
  function prepare(){
    if(preparing)return preparing;
    preparing=(async()=>{const cache=await scope.caches.open(cacheName),controller=new scope.AbortController(),timer=scope.setTimeout(()=>controller.abort(),15000);try{await cache.addAll(urls.map(path=>new scope.Request(new URL(path,scope.location.origin),{cache:'reload',credentials:'omit',signal:controller.signal})));}finally{scope.clearTimeout(timer);}})().finally(()=>{preparing=null;});
    return preparing;
  }
  async function ready(){const cache=await scope.caches.open(cacheName);return (await Promise.all(urls.map(path=>cache.match(new URL(path,scope.location.origin).href)))).every(Boolean);}
  scope.addEventListener('install',event=>event.waitUntil(prepare().catch(async error=>{await scope.caches.delete(cacheName);throw error;})));
  scope.addEventListener('activate',event=>event.waitUntil((async()=>{
    // Keep old packs while other pages may still depend on their chunks.
    const clients=await scope.clients.matchAll({type:'window',includeUncontrolled:true});
    if(clients.length<=1){const old=(await scope.caches.keys()).filter(k=>k.startsWith(prefix)&&k!==cacheName);for(const key of old.slice(0,-1))await scope.caches.delete(key);}
    await scope.clients.claim();
  })()));
  scope.addEventListener('fetch',event=>{
    const request=event.request,url=new URL(request.url);
    if(request.method!=='GET' || url.origin!==scope.location.origin || url.search)return;
    if(request.mode==='navigate' && pages.has(url.pathname)){
      event.respondWith((async()=>{const cache=await scope.caches.open(cacheName);return await cache.match(new URL(pages.get(url.pathname),scope.location.origin).href) || scope.fetch(request);})());return;
    }
    // Immutable static chunks only; never API, model, image, photo or query payloads.
    if(url.pathname.startsWith('/_next/static/') && /\.(js|css|woff2?)$/.test(url.pathname))event.respondWith((async()=>{
      const current=await scope.caches.open(cacheName),cached=await current.match(request);if(cached)return cached;
      for(const key of (await scope.caches.keys()).filter(k=>k.startsWith(prefix)&&k!==cacheName)){const hit=await (await scope.caches.open(key)).match(request);if(hit)return hit;}
      return scope.fetch(request);
    })());
  });
  scope.addEventListener('message',event=>{
    if(typeof event.source?.url!=='string' || !event.ports?.[0])return;
    let source;try{source=new URL(event.source.url);}catch{return;}
    if(source.origin!==scope.location.origin || !pages.has(source.pathname))return;
    const reply=message=>event.ports[0].postMessage(message);
    event.waitUntil((async()=>{
      try{
        if(event.data?.kind==='AGRIRAKSHAK_STATUS')reply({version:pack.version,ready:await ready(),assets:pack.assets});
        else if(event.data?.kind==='AGRIRAKSHAK_PREPARE'){await prepare();reply({version:pack.version,ready:await ready(),assets:pack.assets});}
        else if(event.data?.kind==='AGRIRAKSHAK_APPLY_UPDATE'){
          const clients=await scope.clients.matchAll({type:'window',includeUncontrolled:true});
          if(clients.length>1){reply({error:'Close other tabs for this app before applying the update. Their unsaved edits are not reloaded.'});return;}
          if(!await ready()){reply({error:'The new offline pack is incomplete. Reconnect and prepare it again.'});return;}
          reply({accepted:true});await scope.skipWaiting();
        }
      }catch{reply({error:'Offline app files could not be saved or read. Check your connection and browser storage. Existing farm records were not changed.'});}
    })());
  });
}
