"use client";
import { DocumentLink } from "@/components/document-link";
import { useEffect, useRef, useState } from "react";
import { loadFarm, saveFarm } from "@/lib/storage/farm-store";
import { removeScan } from "@/lib/domain/observations";
import type { Snapshot } from "@/lib/domain/farm";
export function ScanTimeline() {
  const [snapshot,setSnapshot]=useState<Snapshot | null>(null),[cycle,setCycle]=useState("all"),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [deletion,setDeletion]=useState<string | null>(null),[busy,setBusy]=useState(false);const operation=useRef(false);
  useEffect(()=>{let active=true;loadFarm().then(s=>{if(active)setSnapshot(s);}).catch(e=>{if(active)setError(e instanceof Error ? e.message : "Storage unavailable.");});return()=>{active=false;};},[]);
  const scans=snapshot?.scans.filter(s=>cycle==="all" || (cycle==="unlinked" ? s.cycle_id===null : s.cycle_id===cycle)) ?? [];
  async function remove() {
    if (!snapshot || !deletion || operation.current) return;operation.current=true;setBusy(true);setError("");
    try {setSnapshot(await saveFarm(removeScan(snapshot,deletion),snapshot.revision));setDeletion(null);setMessage("Summary deleted from this device.");}
    catch(e){setError(e instanceof Error ? e.message : "Could not delete summary.");}finally{operation.current=false;setBusy(false);}
  }
  return <div className="farm-workspace"><section className="farm-heading"><div><p className="eyebrow">Records on your device</p><h2>Your screening timeline.</h2><p className="lede">Keep screening separate from weather and farming actions. Current entries are demonstrations; no evaluated model is connected.</p></div></section><p className="device-note">Summaries contain no retained photos or coordinates. Export and import them with your farm backup in <DocumentLink href="/farm">My Farm</DocumentLink>.</p>{error && <p role="alert" className="form-error">{error} Reload before retrying.</p>}<div aria-live="polite">{message && <p>{message}</p>}</div>{!snapshot && !error && <p role="status">Loading device records…</p>}<label>Timeline cycle<select value={cycle} onChange={e=>setCycle(e.target.value)}><option value="all">All summaries</option><option value="unlinked">Unlinked summaries</option>{snapshot?.cycles.map(c=><option key={c.id} value={c.id}>{snapshot.fields.find(f=>f.id===c.field_id)?.name} · {c.crop}</option>)}</select></label><section className="farm-card"><h2>Saved summaries</h2>{snapshot && !scans.length && <p>No summaries for this selection. Run the interface demo in the <DocumentLink href="/scan">leaf scanner</DocumentLink>, then explicitly save its summary.</p>}{[...scans].sort((a,b)=>b.screened_at.localeCompare(a.screened_at)||a.id.localeCompare(b.id)).map(s=>{const linked=snapshot!.cycles.find(c=>c.id===s.cycle_id);const field=snapshot!.fields.find(f=>f.id===linked?.field_id);const zone=snapshot!.farms.find(f=>f.id===field?.farm_id)?.timezone ?? "UTC";return <article className="field-item" key={s.id}><span className="simulation-label">{s.availability==="simulation" ? "Interface simulation · no model prediction" : "Model unavailable · no prediction"}</span><h3>{s.demo_label ? `Demo label: ${s.demo_label}` : "No screening result"}</h3><p>{new Date(s.screened_at).toLocaleString("en",{timeZone:zone})} · {zone}</p><p>{linked ? `${field?.name} · ${linked.crop}` : "Unlinked summary"} · {s.model_version}</p><p>No diagnosis or confidence is recorded. This entry does not establish crop suitability or trigger agricultural advice.</p><button disabled={busy} className="text-button" type="button" onClick={()=>setDeletion(s.id)}>Delete summary</button></article>;})}</section>{deletion && <section className="delete-confirm" role="alert"><h2>Delete this screening summary?</h2><p>This cannot be undone without a backup. Crop cycles, reminders and observation notes remain. Linked observations will lose this reference and keep their synthetic label.</p><div className="button-row"><button disabled={busy} className="button button-danger" type="button" onClick={()=>void remove()}>Confirm summary deletion</button><button className="text-button" type="button" onClick={()=>setDeletion(null)}>Keep summary</button></div></section>}</div>;
}
